#!/bin/bash
echo "-> Updating package index..."
sudo apt update
echo "-> Upgrading packages..."
sudo apt upgrade
echo "-> Cleaning up..."
sudo apt autoclean
sudo apt autoremove
rm -f last-upgraded
date > last-upgraded
echo "-> Rebooting (if required)"
sudo test -f /var/run/reboot-required && sudo reboot || echo 'no reboot required'
