# Original source: https://github.com/cbornet/python-httpproblem/blob/7acdedfe06b1243d64e52007f3ee65f0b58d89f6/httpproblem/problem.py
#
# Modifications to original code:
# - Removed support for Python 2
# - Use http module from standard library instead of httplib
# - Removed support for creating AWS-compatible responses
# - Added support for creating Django JSON responses
# - Removed serialization (handled by views)
# - Converted Problem to dataclass
# - Removed problem function
# - Added types
# - Added with_traceback field instead of using a global
# - Added exception field to store the related exception rather than
#   using the current exception
# - By default, use settings.DEBUG to determine whether tracebacks are
#   included
# - Reformatted code using ruff
#
# MIT License
#
# Copyright (c) 2018 Christophe Bornet
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import http
import traceback
from dataclasses import dataclass, field
from typing import Any

from django.conf import settings
from django.http import JsonResponse


@dataclass
class Problem:
    """Reference: https://datatracker.ietf.org/doc/html/rfc7807"""

    status: int
    """The HTTP status code generated by the origin server for this
    occurrence of the problem."""

    type: str = "about:blank"
    """An absolute URI that identifies the problem type. When
    dereferenced, it SHOULD provide human-readable documentation for the
    problem type (e.g., using HTML). When this member is not present its
    value is assumed to be "about:blank"."""

    title: str | None = None
    """A short, human-readable summary of the problem type. It SHOULD
    NOT change from occurrence to occurrence of the problem, except for
    purposes of localization.

    If a title isn't provided, it will be inferred from the HTTP status
    code if the problem type is "about:blank"; otherwise, it defaults to
    "Error".

    """

    detail: str | None = None
    """A human-readable explanation specific to this occurrence of the
    problem."""

    instance: str | None = None
    """An absolute URI that identifies the specific occurrence of the
    problem. It may or may not yield further information if
    dereferenced."""

    exception: Exception | None = None
    """Exception that caused the problem, if applicable."""

    with_traceback: bool = settings.DEBUG
    """Whether to include the exception traceback when converting the
    Problem to a dict."""

    kwargs: dict[str, Any] = field(default_factory=dict)
    """Additional arbitrary fields to include. The field values should
    be JSON serializable."""

    def __post_init__(self):
        if not self.title:
            if self.type == "about:blank" and self.status in http.HTTPStatus:
                status = http.HTTPStatus(int(self.status))
                self.title = status.phrase
            else:
                self.title = "Error"

    def to_dict(self) -> dict[str, Any]:
        """Transforms the Problem into a dict.

        The exception traceback will be included if with_traceback is
        True and an exception was specified.

        :return:
            The problem in dict form.

        """
        result = {
            "status": self.status,
            "type": self.type,
            "title": self.title,
            "detail": self.detail,
            "instance": self.instance,
            **self.kwargs,
        }

        if self.with_traceback and self.exception:
            lines = traceback.format_exception(self.exception)
            result["exception"] = "\n".join(lines)

        return result

    def to_json_response(self) -> JsonResponse:
        """Transforms the Problem into a Django JSON response.

        :return:
            The problem as a Django JSON response.

        """
        data = self.to_dict()
        return JsonResponse(data, status=self.status)
