# Generated by Django 4.1.3 on 2022-11-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangokit_website", "0001_add_page_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("completed", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "todo_item",
            },
        ),
    ]
