[tool.poetry]
name = "djangokit-website"
version = "0.1.0.dev0"
description = "DjangoKit Website"
authors = ["Wyatt Baldwin <Wyatt Baldwin>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "djangokit", from = "src" }
]

include = [
    "src/djangokit/website/**/*.{ts,tsx}",
]

[tool.poetry.dependencies]
python = "^3.9"
djangokit-core = "*"
djangokit-cli = "*"
markdown = "^3.4.1"
pygments = "^2.13.0"
pydantic = "^1.10.2"

[tool.poetry.group.dev.dependencies]
djangokit-core = { path = "../core", develop = true }
djangokit-cli = { path = "../cli", develop = true }

ansible = "^7.1.0"
black = "^22.10.0"
bpython = "^0.23"
isort = "^5.10.1"
mypy = "^0.990"
pytest = "^7.2.0"
runcommands = "^1.0a71"

[tool.runcommands.globals]
env = "development"

[tool.runcommands.envs]
development = {}
production = { host = "djangokit.org" }

[tool.runcommands.args]
# NOTE: These default args allow these commands to be run without
#       needing to specify the env via `run -e production <command>`
ansible.env = "production"
ansible.host = "djangokit.org"

provision.env = "production"
provision.host = "djangokit.org"

prepare.env = "production"
prepare.host = "djangokit.org"

deploy.env = "production"
deploy.host = "djangokit.org"

upgrade_remote.env = "production"
upgrade_remote.host = "djangokit.org"

remote.host = "djangokit.org"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
