[tool.poetry]
name = "org-djangokit-website"
version = "0.0.2.dev0"
description = "DjangoKit.org Website"
authors = ["Wyatt Baldwin <Wyatt Baldwin>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "djangokit", from = "src" }
]

include = [
    "CHANGELOG.md",
]

[tool.poetry.dependencies]
python = "^3.9"
org-djangokit-core = ">=0.0.3.dev0"
org-djangokit-cli = ">=0.0.6.dev0"
markdown = "^3.4.1"
pygments = "^2.14.0"
pydantic = "^1.10.2"
pymemcache = "^4.0.0"

[tool.poetry.group.dev.dependencies]
org-djangokit-core = { path = "../core", develop = true }
org-djangokit-cli = { path = "../cli", develop = true }

ansible = "*"
black = "*"
mypy = "*"
pytest = "*"
ruff = "*"
runcommands = "*"

[tool.make-release.args]
test = false

[tool.runcommands.globals]
env = "production"
host = "djangokit.org"

[tool.runcommands.envs]
development = {}
production = {}

[tool.ruff]
select = ["E", "F", "I"]
ignore = ["E731"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"./commands.py" = ["F722", "F821"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
