[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "org-djangokit-website"
version = "0.0.2.dev0"
description = "DjangoKit.org Website"
authors = [ { name = "Wyatt Baldwin", email = "self@wyattbaldwin.com" } ]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "org-djangokit-core>=0.0.4",
    "org-djangokit-cli>=0.0.7",
    "markdown>=3.4.1",
    "pygments>=2.14.0",
    "pydantic>=1.10.5,<2",
    "pymemcache>=4.0.0",
]

[tool.setuptools.package-data]
"djangokit.website" = [
    "**/*.css",
    "**/*.html",
    "**/*.ico",
    "**/*.js",
    "**/*.jsx",
    "**/*.toml",
    "**/*.ts",
    "**/*.tsx",
]

[tool.uv]
dev-dependencies = [
    "ansible>=8.7.0",
    "mypy>=1.11.2",
    "pytest>=8.3.3",
    "ruff>=0.6.9",
    "runcommands>=1.0a71",
]

[tool.uv.sources]
org-djangokit-core = { path = "../core", editable = true }
org-djangokit-cli = { path = "../cli", editable = true }

[tool.make-release.args]
test = false

[tool.runcommands.globals]
env = "production"
host = "djangokit.org"

[tool.runcommands.envs]
development = {}
production = {}

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E731"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"./commands.py" = ["F722", "F821"]
