[tool.poetry]
name = "org-djangokit-website"
version = "0.1.0.dev0"
description = "DjangoKit.org Website"
authors = ["Wyatt Baldwin <Wyatt Baldwin>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "djangokit", from = "src" }
]

include = [
    "src/djangokit/website/**/*.{ts,tsx}",
]

[tool.poetry.dependencies]
python = "^3.9"
org-djangokit-core = "*"
org-djangokit-cli = "*"
markdown = "^3.4.1"
pygments = "^2.13.0"
pydantic = "^1.10.2"

[tool.poetry.group.dev.dependencies]
org-djangokit-core = { path = "../core", develop = true }
org-djangokit-cli = { path = "../cli", develop = true }

ansible = "^7.1.0"
black = "^22.12.0"
bpython = "^0.23"
isort = "^5.11.2"
mypy = "^0.990"
pytest = "^7.2.0"
ruff = "~0.0.181"
runcommands = "^1.0a71"

[tool.make-release.args]
test = false

[tool.runcommands.globals]
env = "production"
host = "djangokit.org"

[tool.runcommands.envs]
development = {}
production = {}

[tool.ruff]
ignore = [ "E731" ]

[tool.ruff.per-file-ignores]
"__init__.py" = [ "F401" ]
"./commands.py" = [ "F722", "F821" ]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
