[django]
STORAGES.default.BACKEND = "django.core.files.storage.FileSystemStorage"
STORAGES.staticfiles.BACKEND = "djangokit.core.static.ManifestStaticFilesStorage"

[djangokit]
package = "djangokit.website"
title = "DjangoKit!"
description = "DjangoKit - a meta-framework for Django"

global_stylesheets = [
    "lib/bootstrap.css",
    "lib/bootstrap-icons/bootstrap-icons.css",
    "lib/pygments.css",
    "global.css",
]

global_scripts = [
    "lib/bootstrap.bundle.js",
]
